spring.application.name=argos

# MySQL Database URL (replace 'localhost:3306/mydb' with your host, port, and database name)
spring.datasource.url=jdbc:mysql://localhost:3306/argos_db

# Database Credentials
spring.datasource.username=argos_user
spring.datasource.password=sptech

#spring.jpa.hibernate.ddl-auto=update

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Configuração do Servidor de E-mail (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=seu-email@gmail.com
spring.mail.password=sua-senha-de-app
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=3333
